name: drl-gec
channels:
  - pytorch
  - conda-forge
  - defaults
  - huggingface
dependencies:
  - python=3.8.13
  - ipykernel=6.9.1
  - ipywidgets=7.6.3
  - pip>=20.3.3
  - cudatoolkit=11.6
  - pytorch=1.12.0
  - transformers=4.23.1
  - huggingface_hub=0.10.1
  - tensorboard=2.8.0
  - pip:
    - nltk==3.7
    - tqdm==4.62.3
    - cdifflib==1.2.6
    - gym==0.25.1
    - ansi2html==1.8.0
    - streamlit>=1.11.1
    - rapidfuzz==2.11.1
    - autocorrect==2.6.1
    - python-Levenshtein==0.12.2
    - numba==0.56.4
